[package]
name = "rusql"
version = "0.1.0"
authors = ["Manuel Alonso <manuteali@gmail.com>"]
license = "MIT"
description = "A rust library for reusing SQL"
repository = "https://github.com/manute/rusql"
documentation = "http://manute.github.io/rusql/rusql/index.html"
readme = "README.md"
keywords = ["database", "sql"]


[lib]
name = "rusql"
path = "src/lib.rs"
doctest = false

[dev-dependencies]
postgres = "0.10"
